### ISSUE TITLE
Connection Timeout When Connecting to qBittorrent (WebAPI Login Succeeds)

### ISSUE THREAD

**Issue by mehanoid** [tympanix/Electorrent#369]
**Client:**
- [x] qBittorrent
- [ ] µTorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:**
v4.6.7

**Operating System:**
Arch Linux

**Application Version:**
Electorrent 2.8.3

**Description:**
When trying to connect Electorrent to qBittorrent, I get the following error:

```text
Connection problem  
The connection could not be established
```

In the developer tools console, the following message appears:

```text
settings.ts:158 Settings Error Error: Request timed out
    at server.ts:126
```

Full stack trace:
```text
settings.ts:158 Settings Error Error: Request timed out
    at server.ts:126
(anonymous) @ settings.ts:158
processQueue @ angular.js:18075
(anonymous) @ angular.js:18123
$digest @ angular.js:19242
(anonymous) @ angular.js:19562
completeTask @ angular.js:21403
(anonymous) @ angular.js:6879
setTimeout (async)
Browser.self.defer @ angular.js:6877
$evalAsync @ angular.js:19560
(anonymous) @ angular.js:17947
scheduleProcessQueue @ angular.js:18123
$$reject @ angular.js:18179
doReject @ angular.js:18164
Promise.then (async)
$$resolve @ angular.js:18146
resolvePromise @ angular.js:18134
processQueue @ angular.js:18075
(anonymous) @ angular.js:18123
$digest @ angular.js:19242
$apply @ angular.js:19630
(anonymous) @ angular.js:29127
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

However, in the qBittorrent logs I can see that the connection was successfully established:

```text
(N) 2025-04-30T13:38:35 - WebAPI login success. IP: ::ffff:127.0.0.1
```

It seems like the connection is accepted by qBittorrent, but Electorrent runs into a timeout shortly after.

**Comment by tympanix** [comment]
The timeout for connecting is typically 5 seconds. Could it be that you have a lot of data which takes >5 seconds to load? Could you try with a fresh instance of qBittorrent?

We have automatic tests validating the success criteria for logging into qBittorrent which leads me to believe this is not a general issue.

**Comment by tympanix** [comment]
Likely a timeout issue. Was set too short on systems with many torrents.

Addressed in #553

**Comment by mehanoid** [comment]
I finally got around to testing Electorrent 2.11.0, and unfortunately I'm still seeing the same issue.

```
settings-page.controller.ts:202 Settings Error Error: Request timed out
    at server.ts:170:41
(anonymous)	@	settings-page.controller.ts:202
Promise.catch		
(anonymous)	@	settings-page.controller.ts:200
fn	@	VM37:4
(anonymous)	@	angular.js:29123
$eval	@	angular.js:19523
$apply	@	angular.js:19622
(anonymous)	@	angular.js:29127
dispatch	@	jquery.js:5145
(anonymous)	@	jquery.js:4949
```

One additional observation: Electorrent reports `Request timed out` after roughly 3 seconds, but qBittorrent logs show the login succeeding about 6–7 seconds after the attempt. This seems to indicate that qBittorrent on Keenetic/Entware responds slowly enough that Electorrent gives up before the authentication completes.

One thing I find a bit confusing is that the error appears after ~3 seconds, while the login timeout introduced in the PR is 5000 ms. So perhaps a different timeout path is being hit.

For now I'm still using the whitelist-authentication workaround mentioned earlier.

It might be worth making the login timeout configurable, since 5 seconds appears to be insufficient for some low-powered devices.

**Comment by tympanix** [comment]
Thank you @mehanoid 

This was hiding in plain sight - I should have just looked closely at your stack trace.

Will be fixed in #614 and published as a patch release

**Comment by tympanix** [comment]
Released 2.12.1 with a fix

**Comment by mehanoid** [comment]
I tested version 2.12.1 and can confirm that the issue is now resolved for me. Authentication works correctly without using the whitelist.
Thank you for the fix!
